version: '2'

services:
  web:
    image: openmrsvxnaid-vrvu:4.1.73
    env_file:
      - .env
    volumes:
      - web-data:/usr/local/tomcat/.OpenMRS
    ports:
      - "${TOMCAT_PORT}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - shared_network

volumes:
  web-data:
  
networks:
  shared_network:
    name: shared_network
